### ISSUE TITLE
DSi extended header

### ISSUE THREAD

**Issue by Nuck-TH** [Nuck-TH/fwTool#2]
Currently tool is built with it, thus preventing start by minitwlpayload.
This should be disabled, to make tool actually useful.

If i use ndstool with -h 0x200 option(tht is stated to make standard header) - app stops working altogether(guru meditation error on start) while looking valid. So it may be problem not just of ndstool, but of compilation or something else as well.

**Comment by mariogamer2** [comment]
I 'think' this require modifying ndstool itself.

**Comment by Nuck-TH** [comment]
ApacheThunder provided build of hbmenu and fwtool with standard header, so it is possible somehow. But i cant get response from him :( . I prefer to get hints before throwing myself into modifying tools, but it may worth a look anyway.

**Comment by mariogamer2** [comment]
Or maybe simply use an older version of it.

**Comment by Nuck-TH** [comment]
Making .nds with old verion of ndstool(commit [79f6ade](https://github.com/devkitPro/ndstool/commit/79f6ade457f9461fcc7ef64f9b00d0de485f2e4b)) gives same result as new version with -h 0x200 option - white screens in 4swordshax and Guru Meditation in generictwlpayload.

**Comment by mariogamer2** [comment]
Well any user could build an updated version of minitwlpayload.
Billy Acuna posted a build on gbatemp.

**Comment by Nuck-TH** [comment]
Issuue is anyway still present through.

**Comment by billy-acuna** [comment]
What do you mean?
minitwlpayload was just updated by @Apache Thunder to work with newer homebrews with dsi extended header time ago. Just tested with hbmenu 0.6.0 and your fork of fwtool (which I was using early to flash my nand).

**Comment by billy-acuna** [comment]
As for the header, you just need to strip it down. I cannot remember the lenght of the header, sorry about that :/

**Comment by mariogamer2** [comment]
Probably in dsibrew.

**Comment by Nuck-TH** [comment]
Building fwtool with devkitARM r45/libnds 1.5.12 fixes the problem.
Already checked - works on non-updated 4swords minitwlpayload and on generictwlpayload v1.1.
Thanks Apache Thunder for finally giving this hint.
